# -*- coding: utf-8 -*-
"""7scaleproductrev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PUHVGog0TUxlzo0v7QFKKkTJLW9Hz41o
"""

!pip install spacy nltk scikit-learn seaborn matplotlib wordcloud imbalanced-learn
!python -m spacy download en_core_web_sm

import pandas as pd
import numpy as np
import json
import re
import spacy
import nltk
import matplotlib.pyplot as plt
import seaborn as sns

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
from sklearn.svm import LinearSVC
from imblearn.over_sampling import SMOTE
from collections import Counter
from wordcloud import WordCloud
import pickle

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

import pandas as pd
import json

# Read the JSON file line by line to handle potential malformed entries
reviews = []
with open("Cell_Phones_and_Accessories_5.json", 'r') as f:
    for line in f:
        try:
            reviews.append(json.loads(line))
        except json.JSONDecodeError as e:
            print(f"Skipping malformed line: {line.strip()} - Error: {e}")

df = pd.DataFrame(reviews)
df = df[['reviewText', 'overall']]
df.dropna(inplace=True)

print("Total Reviews:", len(df))
df.head()

def label_sentiment(rating):
    return "Positive" if rating >= 4 else "Negative"

df['sentiment'] = df['overall'].apply(label_sentiment)
df['sentiment'].value_counts()

plt.figure()
sns.countplot(x=df['sentiment'])
plt.title("Distribution of Sentiment Classes")
plt.show()

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

negations = {"not", "no", "never"}
stop_words = stop_words - negations

def clean_text(text):
    text = text.lower()
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'[^a-z\s]', '', text)

    words = text.split()
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]

    return " ".join(words)

df['clean_text'] = df['reviewText'].astype(str).apply(clean_text)
df.head()

text = " ".join(df['clean_text'])

wordcloud = WordCloud(width=800, height=400).generate(text)

plt.figure()
plt.imshow(wordcloud)
plt.axis("off")
plt.title("Word Cloud")
plt.show()

nlp_pos = spacy.load("en_core_web_sm", disable=["parser", "ner"])

sample_df = df.sample(n=1000, random_state=42)

feature_list = []

for doc in nlp_pos.pipe(sample_df['reviewText'].astype(str), batch_size=200):
    for token in doc:
        if token.pos_ == "NOUN":
            feature_list.append(token.lemma_.lower())

top_features = Counter(feature_list).most_common(10)

features = [x[0] for x in top_features]
counts = [x[1] for x in top_features]

plt.figure()
sns.barplot(x=counts, y=features)
plt.title("Top Features")
plt.show()

vectorizer = TfidfVectorizer(
    max_features=15000,
    ngram_range=(1,2),
    min_df=3,
    max_df=0.9,
    sublinear_tf=True
)

X = vectorizer.fit_transform(df['clean_text'])
y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nApplying SMOTE...\n")

X_train_dense = X_train.toarray()

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_dense, y_train)

print("Before SMOTE:", X_train.shape)
print("After SMOTE:", X_train_res.shape)

model = LinearSVC()
model.fit(X_train_res, y_train_res)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, pos_label="Positive"))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure()
sns.heatmap(cm, annot=True, fmt='d',
            xticklabels=["Negative","Positive"],
            yticklabels=["Negative","Positive"])
plt.title("Confusion Matrix")
plt.show()

feature_names = vectorizer.get_feature_names_out()
coefficients = model.coef_[0]

top_positive = coefficients.argsort()[-10:][::-1]
top_negative = coefficients.argsort()[:10]

plt.figure()
plt.barh([feature_names[i] for i in top_positive], coefficients[top_positive])
plt.title("Top Positive Words")
plt.show()

plt.figure()
plt.barh([feature_names[i] for i in top_negative], coefficients[top_negative])
plt.title("Top Negative Words")
plt.show()

def get_sentiment_7scale(score):
    if score >= 2:
        return "Strongly Positive"
    elif score >= 1:
        return "Positive"
    elif score > 0:
        return "Slightly Positive"
    elif score == 0:
        return "Neutral"
    elif score > -1:
        return "Slightly Negative"
    elif score > -2:
        return "Negative"
    else:
        return "Strongly Negative"

def predict_review(review):
    cleaned = clean_text(review)
    vector = vectorizer.transform([cleaned])

    prediction = model.predict(vector)[0]
    score = model.decision_function(vector)[0]

    sentiment_7 = get_sentiment_7scale(score)

    return prediction, sentiment_7, score

review = "loved it! best product, must buy for everyone"

pred, sentiment7, score = predict_review(review)

print("\nReview:", review)
print("Binary Prediction:", pred)
print("7-Scale Sentiment:", sentiment7)
print("Confidence Score:", score)

with open("sentiment_model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("\nModel saved successfully!")